import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

import Logo from "@/public/images/logo.png";
import Bars from "@/public/icons/menu.svg";
import Search from "@/public/icons/search.svg";
import Profile from "@/public/images/profile.png";
import Boxes from "@/public/icons/app-grid.svg";
import Sidebar from "./components/SideBar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FinTrack - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FCFDFD] `}
      >
        <nav className="bg-[#FCFDFD]">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-6">
            <div className="flex items-center justify-between h-16">
              <div className="flex items-center gap-4">
                <Image src={Bars} alt="" width={40} height={40} className="w-[24px] h-[24px] " /> <Image src={Logo} width={112} height={32} alt={""} className="w-[112px] " />
              </div>
              <div className="flex items-center space-x-4">
                <button type="button" className="w-[24px] h-[24px] flex items-center justify-center"><Image src={Search} alt="" width={40} height={40} className="w-full " /></button>
                <button type="button" className="w-[24px] h-[24px] flex items-center justify-center"><Image src={Boxes} alt="" width={40} height={40} className="w-full " /></button>
                <div className="w-[40px] h-[40px] flex items-center justify-center overflow-hidden rounded-full"><Image src={Profile} alt="" width={40} height={40} className="w-[40px] object-cover " /></div>
              </div>
            </div>
          </div>
    
        </nav>

        <div className="grid grid-cols-4 gap-[48px] min-h-screen">
          <Sidebar />

          <main className="flex-1 col-span-3">
            {children}
          </main>
        </div>

        
        


      </body>
    </html>
  );
}
